name: lses_tpp_env
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python==3.7.10
  - pytorch==1.12.0 
  - torchvision==0.13.0
  - cudatoolkit==11.3.1
  - cudatoolkit-dev==11.7.0
  - numpy==1.21.5
  - matplotlib==3.5.3
  - pip==22.3.1
  - tqdm==4.64.1
  - gitpython==3.1.30
  - pytest==7.1.2
  - scipy==1.7.3
  - toolz==0.12.0
  - seaborn==0.12.2
  - pip:
    #- tick==0.6.0.0
# https://github.com/X-DataInitiative/tick/releases
#    - https://github.com/X-DataInitiative/tick/releases/download/v0.6/tick-0.6.0.0-cp36-cp36m-manylinux2010_x86_64.whl
    - https://github.com/X-DataInitiative/tick/releases/download/v0.6/tick-0.6.0.0-cp37-cp37m-manylinux2010_x86_64.whl
    - requests==2.28.1
    - dill==0.3.6
    - Pillow==9.5.0
# May need to update conda gcc
# conda install -c anaconda gcc_linux-64
    #- "--editable=git+https://github.com/aliutkus/torchsearchsorted.git@5e70e9f7491ab39b386963264e84492ab4c099c1#egg=torchsearchsorted"
    - imageio==2.31.1
    - pandas==1.3.5
    - scikit-learn==0.22.2.post1
    - tabulate==0.9.0